include:
  - openstack.init.control_base
  - openstack.rabbitmq.server
  - openstack.mysql.server
  - openstack.mysql.init
  - openstack.keystone.server
  - openstack.glance.server
  - openstack.nova.control
  - openstack.horizon.server
  - openstack.neutron.server
  - openstack.cinder.server
